version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /runner
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
